export const userActions = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_ERROR: "USER_SIGNUP_ERROR",

  USER_SIGNIN: "USER_SIGNIN",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_ERROR: "USER_SIGNIN_ERROR",
};
